# Generated by Django 2.2.7 on 2019-11-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creating_profile_for',
            new_name='creatingProfileFor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='middleName',
        ),
    ]
